baseURL = "https://web-coach.pages.dev/"
defaultContentLanguage = "ca"
defaultContentLanguageInSubdir = false

theme = "ananke"

[languages]

  [languages.ca]
    languageName = "Catal√†"
    weight = 1

  [languages.es]
    languageName = "Castellano"
    weight = 2
