backend:
  name: github
  repo: ccasteras@gmail.com/web-coach
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pàgines"
    files:
      - label: "Inici"
        name: "home"
        file: "content/_index.md"
        fields:
          - { label: "Títol", name: "title", widget: "string" }
          - { label: "Contingut", name: "body", widget: "markdown" }
